### ISSUE TITLE
DESCRIBE cars;

### ISSUE THREAD

**Issue by fatum** [LinkedInAttic/sensei#23]
Request made from SensiClientApp:
Post data:
{"bql":"describe cars;"}:

Exception:
2012/01/23 11:38:56.792 INFO [querylog] [] bql=DESCRIBE cars;
2012/01/23 11:38:56.793 ERROR [log] [] /sensei
java.lang.NullPointerException
        at com.senseidb.util.JsonTemplateProcessor.getTemplates(JsonTemplateProcessor.java:18)
        at com.senseidb.util.JsonTemplateProcessor.substituteTemplates(JsonTemplateProcessor.java:38)
        at com.senseidb.util.RequestConverter2.fromJSON(RequestConverter2.java:149)
        at com.senseidb.search.req.SenseiRequest.fromJSON(SenseiRequest.java:626)
        at com.senseidb.servlet.AbstractSenseiClientServlet.handleSenseiRequest(AbstractSenseiClientServlet.java:212)
        at com.senseidb.servlet.AbstractSenseiClientServlet.doGet(AbstractSenseiClientServlet.java:400)
        at com.senseidb.servlet.AbstractSenseiClientServlet.doPost(AbstractSenseiClientServlet.java:424)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2012/01/23 11:39:41.010 INFO [ClientChannelHandler] [] Expired 0 stale entries from the request map

**Comment by fatum** [comment]
wow, request for schema is /sensei/sysinfo
